# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
#Import your libraries

import numpy as np
import pandas as pd

# Introduction

In this lab, we will use two datasets. Both datasets contain variables that describe apps from the Google Play Store. We will use our knowledge in feature extraction to process these datasets and prepare them for the use of a ML algorithm.

# Challenge 1 - Loading and Extracting Features from the First Dataset

#### In this challenge, our goals are: 

* Exploring the dataset.
* Identify the columns with missing values.
* Either replacing the missing values in each column or drop the columns.
* Conver each column to the appropriate type.

#### The first dataset contains different information describing the apps. 

Load the dataset into the variable `google_play` in the cell below. The dataset is in the file `googleplaystore.csv`

In [111]:
# Your code here:

gp = pd.read_csv('../googleplaystore.csv')

#### Examine all variables and their types in the following cell

In [112]:
# Your code here:
gp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

#### Since this dataset only contains one numeric column, let's skip the `describe()` function and look at the first 5 rows using the `head()` function

In [113]:
# Your code here:
gp.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

#### We can see that there are a few columns that could be coerced to numeric.

Start with the reviews column. We can evaluate what value is causing this column to be of object type finding the non-numeric values in this column. To do this, we recall the `to_numeric()` function. With this function, we are able to coerce all non-numeric data to null. We can then use the `isnull()` function to subset our dataframe using the True/False column that this function generates.

In the cell below, transform the Reviews column to numeric and assign this new column to the variable `Reviews_numeric`. Make sure to coerce the errors.

In [115]:
# Your code here:
gp["Reviews_numeric"] = pd.to_numeric(gp["Reviews"], errors="coerce")
gp.loc[gp["Reviews_numeric"] == gp["Reviews_numeric"].isnull()] # 0 and null here are the same thing

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric
478,Truth or Dare Pro,DATING,NaN,0,20M,50+,Paid,$1.49,Teen,Dating,"September 1, 2017",1.0,4.0 and up,0.0
479,"Private Dating, Hide App- Blue for PrivacyHider",DATING,NaN,0,18k,100+,Paid,$2.99,Everyone,Dating,"July 25, 2017",1.0.1,4.0 and up,0.0
621,Dating White Girls,DATING,NaN,0,3.6M,50+,Free,0,Mature 17+,Dating,"July 20, 2018",1.0,4.0 and up,0.0
623,Geeks Dating,DATING,NaN,0,13M,50+,Free,0,Mature 17+,Dating,"July 10, 2018",1.0,4.1 and up,0.0
627,CAM5678 Video Chat,DATING,NaN,0,39M,500+,Free,0,Mature 17+,Dating,"July 13, 2018",5.5.8,4.0.3 and up,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10773,FQ India,LIFESTYLE,NaN,0,8.9M,10+,Free,0,Everyone,Lifestyle,"July 31, 2018",7.2.2,4.1 and up,0.0
10774,Miss FQ,NEWS_AND_MAGAZINES,NaN,0,36M,10+,Free,0,Everyone,News & Magazines,"April 5, 2018",3.8,4.4 and up,0.0
10798,Word Search Tab 1 FR,FAMILY,NaN,0,1020k,50+,Paid,$1.04,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up,0.0
10822,PLMGSS FR,PRODUCTIVITY,NaN,0,3.1M,10+,Free,0,Everyone,Productivity,"December 1, 2017",1,4.4 and up,0.0
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up,0.0

Next, create a column containing True/False values using the `isnull()` function. Assign this column to the `Reviews_isnull` variable.

In [117]:
# Your code here:
gp["Reviews_isnull"] = gp["Reviews_numeric"].isnull()

Finally, subset the `google_play` with `Reviews_isnull`. This should give you all the rows that contain non-numeric characters.

Your output should look like:

![Reviews_bool.png](reviews-bool.png)

In [121]:
# Your code here:
gp[gp["Reviews_isnull"] == True]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3000000.0,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,True

#### We see that Google Play is using a shorthand for millions. 

Let's write a function to transform this data.

Steps:

1. Create a function that returns the correct numeric values of *Reviews*.
1. Define a test string with `M` in the last character.
1. Test your function with the test string. Make sure your function works correctly. If not, modify your functions and test again.

In [119]:
# Your code here

def convert_string_to_numeric(s):
    """
    Convert a string value to numeric. If the last character of the string is `M`, obtain the 
    numeric part of the string, multiply it with 1,000,000, then return the result. Otherwise, 
    convert the string to numeric value and return the result.
    
    Args:
        s: The Reviews score in string format.

    Returns:
        The correct numeric value of the Reviews score.
    """
    
    if s[len(s)-1].upper() == "M":
        return float(s[:len(s)-1]) * 1000000
    else:
        return float(s)

test_string = '4.0M'

convert_string_to_numeric(test_string) == 4000000

True

The last step is to apply the function to the `Reviews` column in the following cell:

In [122]:
# Your code here:
gp.Reviews = gp.Reviews.apply(convert_string_to_numeric)
gp.head()

TypeError: object of type 'float' has no len()

Check the non-numeric `Reviews` row again. It should have been fixed now and you should see:

![Reviews_bool_fixed.png](reviews-bool-fixed.png)

In [123]:
# Your code here
gp.iloc[10472:10473]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3000000.0,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,True

Also check the variable types of `google_play`. The `Reviews` column should be a `float64` type now.

In [124]:
# Your code here:
gp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   App              10841 non-null  object
 1   Category         10841 non-null  object
 2   Rating           9367 non-null   float64
 3   Reviews          10841 non-null  float64
 4   Size             10841 non-null  object
 5   Installs         10841 non-null  object
 6   Type             10840 non-null  object
 7   Price            10841 non-null  object
 8   Content Rating   10840 non-null  object
 9   Genres           10841 non-null  object
 10  Last Updated     10841 non-null  object
 11  Current Ver      10833 non-null  object
 12  Android Ver      10838 non-null  object
 13  Reviews_numeric  10840 non-null  float64
 14  Reviews_isnull   10841 non-null  bool
dtypes: bool(1), float64(3), object(11)
memory usage: 1.2+ MB

#### The next column we will look at is `Size`. We start by looking at all unique values in `Size`:

*Hint: use `unique()` ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.unique.html))*.

In [125]:
# Your code here:
gp.Size.unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '1,000+',
       '470k', '226k', '240k', '89k', '234k', '257k', '861k', '467k',
       '157k', '44k', '676k', '67k', '552k', '885k', '1020k', '582k',
       '619k'], dtype=object)

You should have seen lots of unique values of the app sizes.

#### While we can convert most of the `Size` values to numeric in the same way we converted the `Reviews` values, there is one value that is impossible to convert.

What is that badass value? Enter it in the next cell and calculate the proportion of its occurence to the total number of records of `google_play`.

In [126]:
# Your code here:
"""
There are two values that bother me: 
1- Varies with device 
2- 1.000+
"""

'\nThere are two values that bother me: \n1- Varies with device \n2- 1.000+\n'

In [127]:
gp.Size[gp.Size == "Varies with device"].count() # 1695
# Proportion
gp.Size[gp.Size == "Varies with device"].count() / len(gp) * 100 # 15.63%

gp.Size[gp.Size == "1,000+"].count() # 1695
# Proportion
gp.Size[gp.Size == "1,000+"].count() / len(gp) * 100 # 0.009% -> No relevant

1695

15.635089013928605

1

0.009224241306152568

#### While this column may be useful for other types of analysis, we opt to drop it from our dataset. 

There are two reasons. First, the majority of the data are ordinal but a sizeable proportion are missing because we cannot convert them to numerical values. Ordinal data are both numerical and categorical, and they usually can be ranked (e.g. 82k is smaller than 91M). In contrast, non-ordinal categorical data such as blood type and eye color cannot be ranked. The second reason is as a categorical column, it has too many unique values to produce meaningful insights. Therefore, in our case the simplest strategy would be to drop the column.

Drop the column in the cell below (use `inplace=True`)

In [128]:
# Your code here:
gp.drop(columns=["Size"], inplace=True)
gp.head()

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159.0,False
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967.0,False
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510.0,False
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,215644.0,False
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,967.0,False

#### Now let's look at how many missing values are in each column. 

This will give us an idea of whether we should come up with a missing data strategy or give up on the column all together. In the next column, find the number of missing values in each column: 

*Hint: use the `isna()` and `sum()` functions.*

In [129]:
gp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   App              10841 non-null  object
 1   Category         10841 non-null  object
 2   Rating           9367 non-null   float64
 3   Reviews          10841 non-null  float64
 4   Installs         10841 non-null  object
 5   Type             10840 non-null  object
 6   Price            10841 non-null  object
 7   Content Rating   10840 non-null  object
 8   Genres           10841 non-null  object
 9   Last Updated     10841 non-null  object
 10  Current Ver      10833 non-null  object
 11  Android Ver      10838 non-null  object
 12  Reviews_numeric  10840 non-null  float64
 13  Reviews_isnull   10841 non-null  bool
dtypes: bool(1), float64(3), object(10)
memory usage: 1.1+ MB

In [130]:
# Your code here:
gp.isnull().sum()

App                   0
Category              0
Rating             1474
Reviews               0
Installs              0
Type                  1
Price                 0
Content Rating        1
Genres                0
Last Updated          0
Current Ver           8
Android Ver           3
Reviews_numeric       1
Reviews_isnull        0
dtype: int64

You should find the column with the most missing values is now `Rating`.

#### What is the proportion of the missing values in `Rating` to the total number of records?

Enter your answer in the cell below.

In [131]:
# Your code here:
len(gp.Rating[gp.Rating.isnull()]) / len(gp) *100 # 13.59%

13.596531685268886

A sizeable proportion of the `Rating` column is missing. A few other columns also contain several missing values.

#### We opt to preserve these columns and remove the rows containing missing data.

In particular, we don't want to drop the `Rating` column because:

* It is one of the most important columns in our dataset. 

* Since the dataset is not a time series, the loss of these rows will not have a negative impact on our ability to analyze the data. It will, however, cause us to lose some meaningful observations. But the loss is limited compared to the gain we receive by preserving these columns.

In the cell below, remove all rows containing at least one missing value. Use the `dropna()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html)). Assign the new dataframe to the variable `google_missing_removed`.

In [132]:
gp.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Installs', 'Type', 'Price',
       'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Reviews_numeric', 'Reviews_isnull'],
      dtype='object')

In [133]:
# Your code here:
google_missing_removed = gp.dropna(axis=0 , how="any")
google_missing_removed.head()

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159.0,False
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967.0,False
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510.0,False
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,215644.0,False
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,967.0,False

In [134]:
gpc = google_missing_removed

In [135]:
gpc is google_missing_removed # two different variables ponting to the same object.

True

From now on, we use the `google_missing_removed` variable instead of `google_play`.

#### Next, we look at the `Last Updated` column.

The `Last Updated` column seems to contain a date, though it is classified as an object type. Let's convert this column using the `pd.to_datetime` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html)).

In [136]:
# Your code here:
gpc.loc["Last Updated"] = pd.to_datetime(gpc["Last Updated"])

/home/nicolas/miniconda3/envs/labs_env/lib/python3.7/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [137]:
gpc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9361 entries, 0 to Last Updated
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   App              9360 non-null   object
 1   Category         9360 non-null   object
 2   Rating           9360 non-null   float64
 3   Reviews          9360 non-null   float64
 4   Installs         9360 non-null   object
 5   Type             9360 non-null   object
 6   Price            9360 non-null   object
 7   Content Rating   9360 non-null   object
 8   Genres           9360 non-null   object
 9   Last Updated     9360 non-null   object
 10  Current Ver      9360 non-null   object
 11  Android Ver      9360 non-null   object
 12  Reviews_numeric  9360 non-null   float64
 13  Reviews_isnull   9360 non-null   object
dtypes: float64(3), object(11)
memory usage: 1.1+ MB

#### The last column we will transform is `Price`. 

We start by looking at the unique values of this column.

In [138]:
# Your code here:
gpc.Price.unique()

array(['0', '$4.99', '$3.99', '$6.99', '$7.99', '$5.99', '$2.99', '$3.49',
       '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49', '$10.00',
       '$24.99', '$11.99', '$79.99', '$16.99', '$14.99', '$29.99',
       '$12.99', '$2.49', '$10.99', '$1.50', '$19.99', '$15.99', '$33.99',
       '$39.99', '$3.95', '$4.49', '$1.70', '$8.99', '$1.49', '$3.88',
       '$399.99', '$17.99', '$400.00', '$3.02', '$1.76', '$4.84', '$4.77',
       '$1.61', '$2.50', '$1.59', '$6.49', '$1.29', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$8.49', '$1.75', '$14.00', '$2.00',
       '$3.08', '$2.59', '$19.40', '$3.90', '$4.59', '$15.46', '$3.04',
       '$13.99', '$4.29', '$3.28', '$4.60', '$1.00', '$2.95', '$2.90',
       '$1.97', '$2.56', '$1.20', nan], dtype=object)

Since all prices are ordinal data without exceptions, we can tranform this column by removing the dollar sign and converting to numeric. We can create a new column called `Price Numerical` and drop the original column.

We will achieve our goal in three steps. Follow the instructions of each step below.

#### First we remove the dollar sign. Do this in the next cell by applying the `str.replace` function to the column to replace `$` with an empty string (`''`).

In [139]:
# Your code here:
gpc.loc["Price"] = gpc.Price.str.replace("$", "")
gpc.Price.unique()

array(['0', '$4.99', '$3.99', '$6.99', '$7.99', '$5.99', '$2.99', '$3.49',
       '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49', '$10.00',
       '$24.99', '$11.99', '$79.99', '$16.99', '$14.99', '$29.99',
       '$12.99', '$2.49', '$10.99', '$1.50', '$19.99', '$15.99', '$33.99',
       '$39.99', '$3.95', '$4.49', '$1.70', '$8.99', '$1.49', '$3.88',
       '$399.99', '$17.99', '$400.00', '$3.02', '$1.76', '$4.84', '$4.77',
       '$1.61', '$2.50', '$1.59', '$6.49', '$1.29', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$8.49', '$1.75', '$14.00', '$2.00',
       '$3.08', '$2.59', '$19.40', '$3.90', '$4.59', '$15.46', '$3.04',
       '$13.99', '$4.29', '$3.28', '$4.60', '$1.00', '$2.95', '$2.90',
       '$1.97', '$2.56', '$1.20', nan], dtype=object)

#### Second step, coerce the `Price Numerical` column to numeric.

In [140]:
gpc[gpc.Price.isnull()]

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
Last Updated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
# Your code here:
gpc["Price_Numerical"] = pd.to_numeric(gpc["Price"], errors="coerce")

/home/nicolas/miniconda3/envs/labs_env/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

**Finally, drop the original `Price` column.**

In [142]:
# Your code here:
gpc.drop(columns=["Price"], inplace=True)

/home/nicolas/miniconda3/envs/labs_env/lib/python3.7/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

Now check the variable types of `google_missing_removed`. Make sure:

* `Size` and `Price` columns have been removed.
* `Rating`, `Reviews`, and `Price Numerical` have the type of `float64`.
* `Last Updated` has the type of `datetime64`.

In [143]:
gpc.dropna(inplace=True)

/home/nicolas/miniconda3/envs/labs_env/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [144]:
gpc = gpc.astype({"Rating" : "float64", "Reviews" : "float64"})

In [145]:
# Your code here
gpc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8715 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   App              8715 non-null   object
 1   Category         8715 non-null   object
 2   Rating           8715 non-null   float64
 3   Reviews          8715 non-null   float64
 4   Installs         8715 non-null   object
 5   Type             8715 non-null   object
 6   Content Rating   8715 non-null   object
 7   Genres           8715 non-null   object
 8   Last Updated     8715 non-null   object
 9   Current Ver      8715 non-null   object
 10  Android Ver      8715 non-null   object
 11  Reviews_numeric  8715 non-null   float64
 12  Reviews_isnull   8715 non-null   object
 13  Price_Numerical  8715 non-null   float64
dtypes: float64(4), object(10)
memory usage: 1021.3+ KB

# Challenge 2 - Loading and Extracting Features from the Second Dataset

Load the second dataset to the variable `google_reviews`. The data is in the file `googleplaystore_user_reviews.csv`.

In [2]:
# Your code here:

google_review = pd.read_csv('../googleplaystore_user_reviews.csv')

#### This dataset contains the top 100 reviews for each app. 

Let's examine this dataset using the `head` function

In [3]:
# Your code here
google_review.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

#### The main piece of information we would like to extract from this dataset is the proportion of positive reviews of each app. 

Columns like `Sentiment_Polarity` and `Sentiment_Subjectivity` are not to our interests because we have no clue how to use them. We do not care about `Translated_Review` because natural language processing is too complex for us at present (in fact the `Sentiment`, `Sentiment_Polarity`, and `Sentiment_Subjectivity` columns are derived from `Translated_Review` the data scientists). 

What we care about in this challenge is `Sentiment`. To be more precise, we care about **what is the proportion of *Positive* sentiment of each app**. This will require us to aggregate the `Sentiment` data by `App` in order to calculate the proportions.

Now that you are clear about what we are trying to achieve, follow the steps below that will walk you through towards our goal.

#### Our first step will be to remove all rows with missing sentiment. 

In the next cell, drop all rows with missing data using the `dropna()` function and assign this new dataframe to `review_missing_removed`.

In [4]:
# Your code here:
gr = google_review[["App", "Sentiment"]].copy() # I chose to make a copy instead of dropping columns
gr.head()

                     App Sentiment
0  10 Best Foods for You  Positive
1  10 Best Foods for You  Positive
2  10 Best Foods for You       NaN
3  10 Best Foods for You  Positive
4  10 Best Foods for You  Positive

#### Now, use the `value_counts()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html)) to get a sense on how many apps are in this dataset and their review counts.

In [5]:
# Your code here: 
gr.App.value_counts().count() # 1074 apps

1074

#### Now the tough part comes. Let's plan how we will achieve our goal:

1. We will count the number of reviews that contain *Positive* in the `Sentiment` column.

1. We will create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app.

1. We will then loop the new dataframe to calculate the postivie review portion of each app.

#### Step 1: Count the number of positive reviews.

In the following cell, write a function that takes a column and returns the number of times *Positive* appears in the column. 

*Hint: One option is to use the `np.where()` function ([documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.where.html)).*

In [50]:
d = {"Name": ["Nico", "Kathe", "Nico", "Nico", "Kathe"], "Rate": ["Pos", "Neg", "Neg", "Pos", "Pos"],
    "Age": [2, 5, 2, 2, 5], "Time": [100, 100, 100, 100, 100]}
df = pd.DataFrame(d)
df

    Name Rate  Age  Time
0   Nico  Pos    2   100
1  Kathe  Neg    5   100
2   Nico  Neg    2   100
3   Nico  Pos    2   100
4  Kathe  Pos    5   100

In [73]:
def pos(x):
    p = len(x)
    return p

def power(x):
    return x**2

def add2(x):
    return x["Age"] + x["Time"]

def final(x):
    f = np.where(x.loc[:,"Rate"] == "Pos")
    return len(f[0])

In [88]:
df

    Name Rate  Age  Time  Pos
0   Nico  Pos    2   100    4
1  Kathe  Neg    5   100    5
2   Nico  Neg    2   100    4
3   Nico  Pos    2   100    4
4  Kathe  Pos    5   100    5

In [23]:
df.drop(columns=["Pos"], inplace=True)

In [7]:
np.where((df.loc[:,"Name"] == "Nico") & (df.loc[:,"Rate"] == "Pos"))

(array([0, 3]),)

In [8]:
arr = np.array([[-1, 0, 2], [3, -2, 5]])

In [9]:
np.where(arr>0, arr, -100)

array([[-100, -100,    2],
       [   3, -100,    5]])

In [10]:
gr.Sentiment.unique()

array(['Positive', nan, 'Neutral', 'Negative'], dtype=object)

In [11]:
gr.loc[gr["Sentiment"] == "Neutral"]

                                  App Sentiment
8               10 Best Foods for You   Neutral
9               10 Best Foods for You   Neutral
22              10 Best Foods for You   Neutral
25              10 Best Foods for You   Neutral
29              10 Best Foods for You   Neutral
...                               ...       ...
64189  Hotwire Hotel & Car Rental App   Neutral
64194  Hotwire Hotel & Car Rental App   Neutral
64200  Housing-Real Estate & Property   Neutral
64205  Housing-Real Estate & Property   Neutral
64218  Housing-Real Estate & Property   Neutral

[5163 rows x 2 columns]

In [12]:
app = "10 Best Foods for You"
app = "11st"
pos = np.where((gr.loc[:,"App"] == app) & (gr.loc[:,"Sentiment"] == "Positive"))
tot = np.where((gr.loc[:,"App"] == app))
len(pos[0])
len(tot[0])

23

40

In [91]:
# Your code below

def positive_function(x):
    """
    Count how many times the string `Positive` appears in a column (exact string match).
    Args:
        x: data column
    Returns:
        The number of occurrences of `Positive` in the column data.
    """
    res = []
    names = x["App"].unique()
    
    for name in names:
        pos = np.where((gr.loc[:,"App"] == name) & (gr.loc[:,"Sentiment"] == "Positive"))
        tot = np.where((gr.loc[:,"App"] == name))

        res.append((name, len(pos[0]), len(tot[0])))
    
    return res

pos = positive_function(gr)
pos

[('10 Best Foods for You', 162, 200),
 ('104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室', 31, 40),
 ('11st', 23, 40),
 ('1800 Contacts - Lens Store', 64, 80),
 ('1LINE – One Line with One Touch', 27, 40),
 ('2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif', 25, 40),
 ('21-Day Meditation Experience', 68, 80),
 ('2Date Dating App, Love and matching', 26, 40),
 ('2GIS: directory & navigator', 23, 40),
 ('2RedBeans', 31, 40),
 ('2ndLine - Second Phone Number', 17, 40),
 ('30 Day Fitness Challenge - Workout at Home', 27, 40),
 ('365Scores - Live Scores', 5, 40),
 ('3D Blue Glass Water Keyboard Theme', 0, 40),
 ('3D Color Pixel by Number - Sandbox Art Coloring', 0, 40),
 ('3D Live Neon Weed Launcher', 2, 40),
 ('4 in a Row', 17, 100),
 ('4K Wallpapers and Ultra HD Backgrounds', 7, 40),
 ('591房屋交易-租屋、中古屋、新建案、實價登錄、別墅透天、公寓套房、捷運、買房賣房行情、房價房貸查詢', 5, 40),
 ('591房屋交易-香港', 5, 38),
 ('7 Cups: Anxiety & Stress Chat', 7, 40),
 ('7 Day Food Journal Challenge', 9, 40),
 ('7 Minute Workout', 10, 40),
 ('7 Weeks - Habit & Goal Tracker', 10, 40),
 ('8 Ball Pool', 104, 300),
 ('850 Sports News Digest', 38, 40),
 ('8fit Workouts & Meal Planner', 137, 180),
 ('95Live -SG#1 Live Streaming App', 34, 80),
 ('A Call From Santa Claus!', 20, 80),
 ('A Manual of Acupuncture', 0, 80),
 ('A Word A Day', 3, 40),
 ('A&E - Watch Full Episodes of TV Shows', 30, 120),
 ('A+ Gallery - Photos & Videos', 24, 100),
 ('A+ Mobile', 57, 100),
 ('ABC Kids - Tracing & Phonics', 30, 40),
 ('ABC News - US & World News', 18, 80),
 ('ABC Preschool Free', 19, 40),
 ('ABCmouse.com', 25, 40),
 ('AC - Tips & News for Android™', 18, 40),
 ('ACE Elite', 22, 40),
 ('AD - Nieuws, Sport, Regio & Entertainment', 13, 40),
 ('ADP Mobile Solutions', 0, 40),
 ('ADW Launcher 2', 0, 40),
 ('AMC Theatres', 5, 40),
 ('ANA', 6, 40),
 ('AOL - News, Mail & Video', 17, 40),
 ('AP Mobile - Breaking News', 31, 40),
 ('APE Weather ( Live Forecast)', 25, 40),
 ('APUS Launcher - Theme, Wallpaper, Hide Apps', 25, 40),
 ('ARY NEWS', 18, 40),
 ('ARY NEWS URDU', 19, 40),
 ('ASOS', 52, 80),
 ('ASUS Calling Screen', 9, 40),
 ('ASUS Cover for ZenFone 2', 3, 40),
 ('ASUS Gallery', 0, 40),
 ('ASUS Quick Memo', 1, 40),
 ('ASUS Sound Recorder', 13, 40),
 ('ASUS SuperNote', 14, 40),
 ('AT&T Navigator: Maps, Traffic', 16, 40),
 ('AT&T Smart Wi-Fi', 11, 40),
 ('AT&T Visual Voicemail', 11, 40),
 ('AVG Cleaner – Speed, Battery & Memory Booster', 29, 40),
 ('Abs Training-Burn belly fat', 25, 40),
 ('Account Manager', 11, 40),
 ('Accounting App - Zoho Books', 56, 80),
 ('AccuWeather: Daily Forecast & Live Weather Reports', 23, 40),
 ('Acorn TV: World-class TV from Britain and Beyond', 14, 40),
 ('Acorns - Invest Spare Change', 2, 80),
 ('Acupuncture Assistant', 0, 34),
 ('AdWords Express', 20, 80),
 ('Ada - Your Health Guide', 54, 80),
 ('Add Text To Photo', 18, 40),
 ('Adobe Acrobat Reader', 119, 180),
 ('Adobe Photoshop Express:Photo Editor Collage Maker', 32, 80),
 ('Adult Dating - AdultFinder', 0, 40),
 ('Adult Glitter Color by Number Book - Sandbox Pages', 0, 40),
 ('Advanced Task Killer', 11, 40),
 ('Agar.io', 60, 200),
 ('Age Calculator', 19, 40),
 ('Agoda – Hotel Booking Deals', 30, 40),
 ('Air Traffic', 16, 40),
 ('AirAsia', 8, 40),
 ('AirBrush: Easy Photo Editor', 17, 100),
 ('Airbnb', 36, 120),
 ('Airport + Flight Tracker Radar', 13, 40),
 ('Airway Ex - Intubate. Anesthetize. Train.', 25, 40),
 ('Akinator', 19, 40),
 ('AlReader -any text book reader', 24, 40),
 ('Alarm Clock', 22, 40),
 ('Alarm Clock Free', 19, 40),
 ('Alfred Home Security Camera', 21, 40),
 ('AliExpress - Smarter Shopping, Better Living', 29, 120),
 ('All Email Providers', 3, 40),
 ('All Events in City', 23, 40),
 ('All Football - Latest News & Videos', 27, 40),
 ('All Football GO- Live Score, Games', 30, 40),
 ('All Language Translator Free', 24, 40),
 ('All Maths Formulas', 26, 40),
 ('All Mental disorders', 43, 80),
 ('All Social Networks', 12, 40),
 ('All Video Downloader 2018', 23, 40),
 ('All-In-One Toolbox: Cleaner, Booster, App Manager', 15, 40),
 ('All-in-One Mahjong 3 FREE', 1, 40),
 ('AllTrails: Hiking, Running & Mountain Bike Trails', 0, 40),
 ('Allegiant', 2, 40),
 ('Allrecipes Dinner Spinner', 16, 40),
 ("Alto's Adventure", 103, 200),
 ('Amazon Drive', 18, 40),
 ('Amazon FreeTime – Kids’ Videos, Books, & TV shows', 28, 40),
 ('Amazon Kindle', 65, 140),
 ('Amazon Prime Video', 2, 40),
 ('Amazon Shopping', 22, 180),
 ('Amazon for Tablets', 10, 40),
 ('American Airlines', 20, 80),
 ('Amex Mobile', 20, 40),
 ('Amino: Communities and Chats', 23, 40),
 ('Amtrak', 11, 40),
 ('Anatomy Learning - 3D Atlas', 28, 40),
 ('Ancestry', 28, 40),
 ('AndroZip™ FREE File Manager', 21, 40),
 ('Android Auto - Maps, Media, Messaging & Voice', 30, 40),
 ('Android Messages', 23, 80),
 ('Anger of stick 5 : zombie', 2, 100),
 ('Angry Birds 2', 16, 40),
 ('Angry Birds Classic', 124, 320),
 ('Angry Birds Rio', 15, 120),
 ('Animal Jam - Play Wild!', 0, 40),
 ('Animal Planet GO', 14, 40),
 ('Animated Photo Editor', 21, 40),
 ('Anime Avatar Creator: Make Your Own Avatar', 18, 40),
 ('Anime Manga Coloring Book', 19, 40),
 ('Anthem Anywhere', 19, 80),
 ('Anthem BC Anywhere', 8, 40),
 ('Any.do: To-do list, Calendar, Reminders & Planner', 74, 180),
 ('Apartment Decorating Ideas', 1, 40),
 ('Apartment List: Housing, Apt, and Property Rentals', 42, 80),
 ('Apartment, Home Rental Search: Realtor.com Rentals', 12, 40),
 ('Apartments & Rentals - Zillow', 28, 80),
 ('Apartments.com Rental Search', 32, 80),
 ('Apex Launcher', 37, 80),
 ('Apk Installer', 18, 40),
 ('App vault', 8, 80),
 ('AppLock', 6, 40),
 ('AppLock - Fingerprint', 16, 40),
 ('Apple Daily 蘋果動新聞', 13, 40),
 ('Aprender inglés con Wlingua', 53, 80),
 ('Archos File Manager', 14, 40),
 ('Arrow.io', 53, 100),
 ('Asana: organize team projects', 33, 80),
 ('Ascape VR: 360° Virtual Travel', 10, 40),
 ('Asphalt 8: Airborne', 39, 100),
 ('Associated Credit Union Mobile', 30, 40),
 ('Asteroids 3D live wallpaper', 21, 40),
 ('Atlan3D Navigation: Korea navigator', 23, 40),
 ('AutoCAD - DWG Viewer & Editor', 16, 40),
 ('AutoScout24 Switzerland – Find your new car', 30, 100),
 ('Avakin Life - 3D virtual world', 52, 100),
 ('Aviary Effects: Classic', 26, 40),
 ('Aviary Stickers: Free Pack', 23, 40),
 ('Azar', 38, 100),
 ('Azpen eReader', 15, 32),
 ('B612 - Beauty & Filter Camera', 9, 80),
 ('BBC Media Player', 12, 40),
 ('BBC News', 37, 120),
 ('BBC Sport', 33, 80),
 ('BBM - Free Calls & Messages', 18, 40),
 ('BBVA Compass Banking', 17, 40),
 ('BBVA Spain', 27, 40),
 ('BBW Dating & Curvy Singles Chat- LargeFriends', 45, 80),
 ('BBW Dating & Plus Size Chat', 69, 120),
 ('BBWCupid - BBW Dating App', 21, 40),
 ('BELONG Beating Cancer Together', 28, 40),
 ('BEST CAR SOUNDS', 25, 43),
 ('BET NOW - Watch Shows', 39, 120),
 ('BEYBLADE BURST app', 16, 40),
 ('BIG Launcher', 26, 40),
 ('BLK - Swipe. Match. Chat.', 27, 40),
 ('BZWBK24 mobile', 14, 40),
 ('BaBe - Baca Berita', 10, 40),
 ('BaBe Lite - Baca Berita Hemat Kuota', 8, 40),
 ('BaBe+ - Berita Indonesia', 13, 40),
 ('Babbel – Learn Languages', 34, 120),
 ('Babbel – Learn Spanish', 33, 40),
 ('Baby ABC in box! Kids alphabet games for toddlers!', 29, 40),
 ('Baby Monitor', 27, 40),
 ('Baby Name Together', 25, 40),
 ('Baby Panda Care', 32, 80),
 ('Baby Panda Learns Shapes', 19, 40),
 ('Baby Panda Musical Genius', 22, 40),
 ('Baby Panda’s Juice Shop', 3, 40),
 ('Baby Sleep: White noise lullabies for newborns', 0, 40),
 ('Baby Tiger Care - My Cute Virtual Pet Friend', 5, 40),
 ('Baby puzzles', 16, 40),
 ('Baca- Berita Terbaru, Informasi, Gosip dan Politik', 21, 40),
 ('Backgrounds (HD Wallpapers)', 23, 40),
 ('Backgrounds HD (Wallpapers)', 18, 40),
 ('BaconReader for Reddit', 24, 40),
 ('Bad Piggies', 37, 100),
 ('Badoo - Free Chat & Dating App', 58, 120),
 ('Bagan - Myanmar Keyboard', 21, 40),
 ('Banco Itaú', 18, 40),
 ('Banco do Brasil', 22, 40),
 ('Bancomer móvil', 11, 40),
 ('Banfield Pet Health Tracker', 46, 80),
 ('Bangla Newspaper – Prothom Alo', 20, 40),
 ('Banjo', 27, 40),
 ('Bank of America Mobile Banking', 22, 40),
 ('BankMobile Vibe App', 19, 40),
 ('Banorte Movil', 17, 40),
 ('Banque Populaire', 5, 40),
 ('Barbie Life™', 11, 40),
 ('Barbie Magical Fashion', 18, 40),
 ('Barbie™ Fashion Closet', 43, 80),
 ('Barclays US for Android', 15, 40),
 ('Barcode Scanner', 31, 40),
 ('Baritastic - Bariatric Tracker', 34, 40),
 ('Baseball Boy!', 20, 40),
 ('Basketball FRVR - Shoot the Hoop and Slam Dunk!', 16, 40),
 ('Basketball Stars', 44, 100),
 ('Bathroom Decorating Ideas', 25, 40),
 ('Battlelands Royale', 53, 100),
 ('Be A Legend: Soccer', 33, 100),
 ('BeSoccer - Soccer Live Score', 25, 40),
 ('BeWild Free Dating & Chat App', 31, 40),
 ('Beautiful Design Birthday Cake', 21, 40),
 ('Beautiful Widgets Free', 20, 40),
 ('Beautiful Widgets Pro', 30, 40),
 ('Beauty Camera - Selfie Camera', 23, 40),
 ('Beauty Makeup Snappy Collage Photo Editor - Lidow', 2, 40),
 ('Beauty Makeup – Photo Makeover', 0, 40),
 ('Beauty Selfie Camera', 0, 100),
 ('BeautyPlus - Easy Photo Editor & Selfie Camera', 2, 160),
 ('Bed Time Fan - White Noise Sleep Sounds', 1, 40),
 ('Bedroom Decorating Ideas', 0, 40),
 ('Been Together (Ad) - D-day', 0, 40),
 ('Best Buy', 0, 40),
 ('Best Car Wallpapers', 1, 100),
 ('Best Fiends - Free Puzzle Game', 1, 80),
 ('Best New Ringtones 2018 Free 🔥 For Android™', 0, 40),
 ('Best Ovulation Tracker Fertility Calendar App Glow', 1, 40),
 ('Best Wallpapers Backgrounds(100,000+ 4K HD)', 6, 40),
 ('Best Wallpapers QHD', 30, 40),
 ('BestCam Selfie-selfie, beauty camera, photo editor', 28, 100),
 ('BetterMe: Weight Loss Workouts', 27, 40),
 ('Betterment', 25, 40),
 ('BeyondMenu Food Delivery', 35, 40),
 ('BeyondPod Podcast Manager', 32, 40),
 ('Bible', 81, 100),
 ('Big Days - Events Countdown', 24, 40),
 ('BigOven Recipes, Meal Planner, Grocery List & More', 34, 40),
 ('BiggerCity: Chat for gay bears, chubs & chasers', 27, 40),
 ('Bike Computer - GPS Cycling Tracker', 27, 40),
 ('Binaural Beats Meditation', 29, 40),
 ('Binaural Beats Therapy', 28, 40),
 ('BioLife Plasma Services', 24, 40),
 ('Birdays – Birthday reminder', 33, 40),
 ('Birds Sounds Ringtones & Wallpapers', 27, 40),
 ('Black People Meet Singles Date', 19, 80),
 ('Black Wallpaper, AMOLED, Dark Background: Darkify', 0, 40),
 ('Black White Interracial Dating - Interracial Match', 0, 80),
 ("Blackpink as if it's your last", 0, 40),
 ('Bleacher Report: sports news, scores, & highlights', 0, 200),
 ('Blendr - Chat, Flirt & Meet', 0, 80),
 ('Blibli.com Belanja Online', 0, 40),
 ('Blidz - Hunt Free Deals On Trending Items!', 0, 40),
 ('Blinkist - Nonfiction Books', 0, 40),
 ('Blitzer.de', 0, 40),
 ('Block Craft 3D: Building Simulator Games For Free', 0, 80),
 ('Block Puzzle', 83, 220),
 ('Block Puzzle Classic Legend !', 46, 80),
 ('Blogaway for Android (Blogger)', 19, 40),
 ('Blogger', 31, 40),
 ("Bloglovin'", 19, 40),
 ('Blood Donor', 26, 40),
 ('Blood Pressure', 31, 40),
 ('Blood Pressure Log - MyDiary', 35, 40),
 ('Blood Pressure(BP) Diary', 14, 40),
 ('Bloomberg Professional', 15, 40),
 ('Bloomberg: Market & Financial News', 15, 40),
 ('Blossom Blast Saga', 17, 40),
 ('BluTV', 16, 40),
 ('Blue CareOnDemand', 0, 40),
 ('BlueJeans for Android', 0, 40),
 ('Bluebird by American Express', 0, 40),
 ('Blur Image Background', 8, 40),
 ('Blur Image Background Editor (Blur Photo Editor)', 26, 40),
 ('Booking.com Travel Deals', 54, 120),
 ('Bowmasters', 169, 320),
 ('Box', 81, 120),
 ('Boxed Wholesale', 30, 40),
 ("Boys Photo Editor - Six Pack & Men's Suit", 23, 40),
 ('Brain Waves - Binaural Beats', 32, 40),
 ('Branch', 28, 40),
 ('Brasileirão Pro 2018 - Série A e B', 34, 40),
 ('Breaking News, Local news, Attacks and Alerts Free', 14, 40),
 ('Breathing Zone', 0, 40),
 ('Bricks n Balls', 0, 40),
 ('Brightest Flashlight - LED Light', 0, 40),
 ('Brightest Flashlight Free ®', 5, 40),
 ('Brightest LED Flashlight', 13, 40),
 ('Brilliant', 21, 80),
 ('Brit + Co', 10, 40),
 ('British Airways', 13, 40),
 ('Browser 4G', 23, 40),
 ('Bualuang mBanking', 11, 40),
 ('Bubble Shooter', 100, 260),
 ('Bubble Shooter 2', 8, 80),
 ('Bubble Shooter Genies', 6, 40),
 ('Bubble Shooter Space', 14, 40),
 ('Bubble Witch 3 Saga', 19, 40),
 ('Buienradar - weer', 20, 40),
 ('Build a Bridge!', 50, 100),
 ('Bukalapak - Jual Beli Online', 14, 40),
 ('BukuBayi - Perkembangan Bayi', 21, 40),
 ('Burner - Free Phone Number', 5, 40),
 ('Bus Rush: Subway Edition', 0, 40),
 ('Buscapé - Ofertas e descontos', 2, 40),
 ('Business Calendar 2', 18, 40),
 ('Butterfly Live Wallpaper', 20, 40),
 ('Buzz Launcher-Smart&Free Theme', 25, 40),
 ('BuzzFeed: News, Tasty, Quizzes', 47, 80),
 ('BÁO MỚI - Đọc Báo, Tin Tức 24h', 18, 40),
 ('C Programming', 32, 40),
 ('C++ Programming', 24, 40),
 ('C++ Tutorials', 32, 40),
 ('CAIXA', 11, 40),
 ('CALCU™ Stylish Calculator Free', 27, 40),
 ('CATS: Crash Arena Turbo Stars', 35, 100),
 ('CBS - Full Episodes & Live TV', 0, 80),
 ('CBS News', 0, 40),
 ('CBS Sports App - Scores, News, Stats & Watch Live', 123, 320),
 ('CBS Sports Fantasy', 34, 80),
 ('CDL Practice Test 2018 Edition', 21, 40),
 ('CIA - Caller ID & Call Blocker', 8, 40),
 ('CM Browser - Ad Blocker , Fast Download , Privacy', 1, 40),
 ('CM FILE MANAGER HD', 0, 40),
 ('CM Flashlight (Compass, SOS)', 4, 40),
 ('CM Launcher 3D - Theme, Wallpapers, Efficient', 12, 40),
 ('CM Locker - Security Lockscreen', 56, 100),
 ('CMB Free Dating App', 55, 80),
 ('CNBC: Breaking Business News & Live Market Data', 25, 40),
 ('CNN Breaking US & World News', 65, 120),
 ("COOKING MAMA Let's Cook!", 26, 40),
 ('CVS Caremark', 23, 40),
 ('CW Seed', 25, 40),
 ('CWT To Go', 28, 40),
 ('Cache Cleaner-DU Speed Booster (booster & cleaner)', 16, 40),
 ('Caf - Mon Compte', 1, 33),
 ('Calculator', 0, 40),
 ('Calculator ++', 0, 40),
 ('Calculator - free calculator ,multi calculator app', 0, 38),
 ('Calculator - free calculator, multi calculator app', 1, 40),
 ('Calculator - unit converter', 1, 40),
 ('Calculator Plus Free', 2, 40),
 ('Calculator with Percent (Free)', 1, 40),
 ('Calendar Widget Month + Agenda', 1, 40),
 ('Calendar+ Schedule Planner App', 1, 40),
 ('Call Blocker', 1, 80),
 ('Call Control - Call Blocker', 0, 40),
 ('Call Free – Free Call', 0, 40),
 ('Call of Duty:Black Ops Zombies', 0, 40),
 ('CallApp: Caller ID, Blocker & Phone Call Recorder', 1, 40),
 ('Caller ID +', 1, 40),
 ('Calls & Text by Mo+', 5, 80),
 ('Calls Blacklist - Call Blocker', 2, 40),
 ('Calm - Meditate, Sleep, Relax', 56, 80),
 ('Calorie Counter & Diet Tracker', 109, 140),
 ('Calorie Counter - EasyFit free', 33, 40),
 ('Calorie Counter - Macros', 174, 200),
 ('Calorie Counter - MyFitnessPal', 169, 260),
 ('Calorie Counter - MyNetDiary', 120, 200),
 ('Calorie Counter by FatSecret', 0, 200),
 ('Camera FV-5', 0, 40),
 ('Camera FV-5 Lite', 0, 40),
 ('Camera MX - Free Photo & Video Camera', 0, 40),
 ('Camera ZOOM FX - FREE', 0, 40),
 ('Camera for Android', 0, 120),
 ('Camera360 Lite - Selfie Camera', 0, 40),
 ('Camera360: Selfie Photo Editor with Funny Sticker', 0, 120),
 ('Camera51 - a smarter camera', 0, 40),
 ('Cameringo Lite. Filters Camera', 8, 80),
 ('Candy Bomb', 62, 80),
 ('Candy Camera - selfie, beauty camera, photo editor', 73, 120),
 ('Candy Crush Jelly Saga', 21, 80),
 ('Candy Crush Saga', 102, 240),
 ('Candy Crush Soda Saga', 62, 180),
 ('Candy Day', 26, 40),
 ('Candy Pop Story', 22, 40),
 ('Candy Smash', 28, 40),
 ('Candy selfie - photo editor, live filter camera', 21, 40),
 ('Canva: Poster, banner, card maker & graphic design', 30, 40),
 ('Canvas Student', 2, 40),
 ('Capital One® Mobile', 0, 80),
 ('Capitec Remote Banking', 0, 40),
 ('CarMax – Cars for Sale: Search Used Car Inventory', 0, 100),
 ('Card Wars - Adventure Time', 0, 40),
 ('Cardboard', 0, 40),
 ('CareZone', 0, 40),
 ('Carousell: Snap-Sell, Chat-Buy', 0, 80),
 ('Cars: Lightning League', 0, 40),
 ('Cartoon Network App', 0, 40),
 ('Cash App', 0, 40),
 ('Cash, Inc. Money Clicker Game & Business Adventure', 0, 40),
 ('Castle Clash: Heroes of the Empire US', 0, 40),
 ('Castlight Mobile', 0, 40),
 ('Casual Dating & Adult Singles - Joyride', 0, 80),
 ('Cat Sim Online: Play with Cats', 45, 100),
 ('Caviar - Food Delivery', 25, 40),
 ('Chakra Cleansing', 35, 40),
 ('Championat', 25, 40),
 ('Chapters: Interactive Stories', 30, 40),
 ('Chase Mobile', 23, 40),
 ('Chat Rooms, Avatars, Date - Galaxy', 46, 80),
 ('ChatVideo Meet new people', 20, 40),
 ('Cheap Flights & Hotels momondo', 24, 40),
 ('Cheap hotel deals and discounts — Hotellook', 24, 40),
 ('CheapTickets – Hotels, Flights & Travel Deals', 27, 40),
 ('Cheapflights – Flight Search', 28, 40),
 ('CheckPoints 🏆 Rewards App', 28, 40),
 ('Checkers ✔️', 18, 40),
 ('Checkout 51: Grocery coupons', 21, 120),
 ('ChefTap Recipes & Grocery List', 0, 40),
 ('Chefkoch - Rezepte & Kochen', 0, 40),
 ('Chegg Study - Homework Help', 0, 40),
 ('Chess Free', 0, 40),
 ('Chess PRO Free', 0, 40),
 ('Chess School for Beginners', 0, 40),
 ('Chess for Kids - Play & Learn', 0, 40),
 ('Chicago Tribune', 0, 40),
 ('Chick-fil-A', 0, 120),
 ('Chictopia', 0, 80),
 ('Chilindo', 0, 40),
 ('Chime - Mobile Banking', 0, 40),
 ('Chispa, the Dating App for Latino, Latina Singles', 0, 80),
 ('Choice Hotels', 7, 40),
 ('Choices: Stories You Play', 21, 40),
 ('Christian Dating For Free App', 50, 80),
 ('Chrome Beta', 22, 40),
 ('Chrome Dev', 25, 40),
 ('Cinemark Theatres', 20, 40),
 ('Cisco Webex Meetings', 22, 40),
 ('Cisco Webex Teams', 18, 40),
 ('Citi Mobile®', 20, 40),
 ('Citibanamex Movil', 24, 40),
 ('Citizens Bank Mobile Banking', 18, 40),
 ('CityMaps2Go Plan Trips Travel Guide Offline Maps', 32, 40),
 ('Claro', 11, 40),
 ('Clash Royale', 107, 180),
 ('Clash of Clans', 23, 180),
 ('ClassDojo', 0, 180),
 ('Classic Calculator', 0, 40),
 ('Classical music for baby', 0, 40),
 ('ClearCareGo Caregiver', 0, 40),
 ('ClickMeeting Webinars', 0, 40),
 ('Cloud Print', 0, 40),
 ('Clover Dating App', 0, 80),
 ('Club Factory Everything, Unbeaten Price', 0, 40),
 ('Clue', 0, 40),
 ('Collage&Add Stickers papelook', 0, 40),
 ('Color Call - Caller Screen, LED Flash', 0, 40),
 ('Color Flashlight', 7, 40),
 ('Color Road', 14, 40),
 ('Color Touch Effects', 19, 40),
 ('Color by Number - Draw Sandbox Pixel Art', 55, 100),
 ('Color by Number – New Coloring Book', 33, 40),
 ('ColorFil - Adult Coloring Book', 24, 40),
 ('ColorNote Notepad Notes', 121, 140),
 ('ColorSnap® Visualizer', 13, 40),
 ('Colorfit - Drawing & Coloring', 29, 40),
 ('Colorful Glitter Neon Butterfly Keyboard Theme', 17, 40),
 ('Colorfy: Coloring Book for Adults - Free', 81, 140),
 ('Coloring & Learn', 31, 40),
 ('Coloring book moana', 26, 58),
 ('Comedy Central', 42, 80),
 ('Common Core', 4, 40),
 ('CompTIA A+ Pocket Prep', 0, 40),
 ('CompTIA Exam Training', 0, 40),
 ('Compass', 0, 40),
 ('Comptia A+ 220-901 & 220-902', 26, 69),
 ('ConnectLine', 26, 40),
 ('Contacts', 16, 40),
 ('Contacts+', 27, 40),
 ('Content Transfer', 22, 40),
 ('ConvertPad - Unit Converter', 29, 40),
 ('Cookbook Recipes', 35, 40),
 ('Cooking Channel', 29, 40),
 ('Cooking Fever', 55, 140),
 ("Cooking Madness - A Chef's Restaurant Games", 20, 40),
 ('Cookpad', 26, 40),
 ('Cool Popular Ringtones 2018 🔥', 24, 40),
 ('Cool Reader', 24, 40),
 ('Couch to 10K Running Trainer', 36, 40),
 ('Couch to 5K by RunDouble', 28, 40),
 ('Couchsurfing Travel App', 29, 40),
 ('Cougar Dating Life : Date Older Women Sugar Mummy', 56, 80),
 ('Couple - Relationship App', 23, 80),
 ('Coupon Sherpa', 0, 40),
 ('Coupons.com – Grocery Coupons & Cash Back Savings', 0, 100),
 ('Coursera: Online courses', 0, 80),
 ('Cover Fire: offline shooting games for free', 0, 100),
 ('Cozi Family Organizer', 0, 40),
 ('CppDroid - C/C++ IDE', 0, 40),
 ('Crackle - Free TV & Movies', 0, 120),
 ('Crazy Colors: Bubbles Matching', 0, 40),
 ('Create A Superhero HD', 0, 100),
 ('Creative Ideas - DIY & Craft', 0, 40),
 ('Credit Karma', 27, 80),
 ('Credit Sesame', 21, 40),
 ('CreditWise from Capital One', 28, 40),
 ('Crew - Free Messaging and Scheduling', 72, 80),
 ('Cricbuzz - Live Cricket Scores & News', 26, 40),
 ('Cricket Visual Voicemail', 20, 40),
 ('Crossy Road', 67, 100),

In [ ]:
# Como utilizo apply cuando tengo una funcion con multiples argumentos y no quiero usar lambda??

#### Step 2: Create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app

We will group `review_missing_removed` by the `App` column, then aggregate the grouped dataframe on the number of positive reviews and the total review counts of each app. The result will be assigned to a new variable `google_agg`. Here is the ([documentation on how to achieve it](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.DataFrameGroupBy.agg.html)). Take a moment or two to read the documentation and google examples because it is pretty complex.

When you obtain `google_agg`, check its values to make sure it has an `App` column as its index as well as a `Positive` column and a `Total` column. Your output should look like:

![Positive Reviews Agg](positive-review-agg.png)

*Hint: Use `positive_function` you created earlier as part of the param passed to the `agg()` function in order to aggregate the number of positive reviews.*

#### Bonus:

As of Pandas v0.23.4, you may opt to supply an array or an object to `agg()`. If you use the array param, you'll need to rename the columns so that their names are `Positive` and `Total`. Using the object param will allow you to create the aggregated columns with the desirable names without renaming them. However, you will probably encounter a warning indicating supplying an object to `agg()` will become outdated. It's up to you which way you will use. Try both ways out. Any way is fine as long as it works.

In [104]:
# Your code here:
gr_agg = pd.DataFrame(pos, columns=["App", "Positive", "Total"])
gr_gb = gr_agg.groupby("App").sum()
gr_gb.head()

                                  Positive  Total
App
10 Best Foods for You                  162    200
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室        31     40
11st                                    23     40
1800 Contacts - Lens Store              64     80
1LINE – One Line with One Touch         27     40

#### Print the first 5 rows of `google_agg` to check it.

In [105]:
# Your code here
gr_gb.head()

                                  Positive  Total
App
10 Best Foods for You                  162    200
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室        31     40
11st                                    23     40
1800 Contacts - Lens Store              64     80
1LINE – One Line with One Touch         27     40

#### Add a derived column to `google_agg` that is the ratio of the `Positive` and the `Total` columns. Call this column `Positive Ratio`. 

Make sure to account for the case where the denominator is zero using the `np.where()` function.

In [106]:
# Your code here:

# lo mismo. como uso apply sin usar lambda con una function con multiples argumentos. la de arriba mejor

def pos_ratio(x):
    if x["Total"] == 0:
        return 0
    else:
        return x["Positive"] / x["Total"]

gr_gb["Positive Ratio"] = gr_gb.apply(pos_ratio, axis=1)
gr_gb.head()

                                  Positive  Total  Positive Ratio
App
10 Best Foods for You                  162    200           0.810
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室        31     40           0.775
11st                                    23     40           0.575
1800 Contacts - Lens Store              64     80           0.800
1LINE – One Line with One Touch         27     40           0.675

#### Now drop the `Positive` and `Total` columns. Do this with `inplace=True`.

In [109]:
# Your code here:
gr_gb.drop(columns=["Positive", "Total"], axis=1, inplace=True)

                                  Positive Ratio
App
10 Best Foods for You                      0.810
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室           0.775
11st                                       0.575
1800 Contacts - Lens Store                 0.800
1LINE – One Line with One Touch            0.675

Print the first 5 rows of `google_agg`. Your output should look like:

![Positive Reviews Agg](positive-review-ratio.png)

In [110]:
# Your code here:
gr_gb.head()

                                  Positive Ratio
App
10 Best Foods for You                      0.810
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室           0.775
11st                                       0.575
1800 Contacts - Lens Store                 0.800
1LINE – One Line with One Touch            0.675

# Challenge 3 - Join the Dataframes

In this part of the lab, we will join the two dataframes and obtain a dataframe that contains features we can use in our ML algorithm.

In the next cell, join the `google_missing_removed` dataframe with the `google_agg` dataframe on the `App` column. Assign this dataframe to the variable `google`.

In [148]:
# Your code here:
google = pd.merge(gpc, gr_gb, how="inner", on="App")

#### Let's look at the final result using the `head()` function. Your final product should look like:

![Final Product](google-final-head.png)

In [149]:
# Your code here:
google.head()

,App,Category,Rating,Reviews,Installs,Type,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull,Price_Numerical,Positive Ratio
0,Coloring book moana,ART_AND_DESIGN,3.9,967.0,"500,000+",Free,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967.0,False,0.0,0.448276
1,Coloring book moana,FAMILY,3.9,974.0,"500,000+",Free,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,974.0,False,0.0,0.448276
2,Garden Coloring Book,ART_AND_DESIGN,4.4,13791.0,"1,000,000+",Free,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up,13791.0,False,0.0,0.640000
3,3D Color Pixel by Number - Sandbox Art Coloring,ART_AND_DESIGN,4.4,1518.0,"100,000+",Free,Everyone,Art & Design,"August 3, 2018",1.2.3,2.3 and up,1518.0,False,0.0,0.000000
4,FlipaClip - Cartoon animation,ART_AND_DESIGN,4.3,194216.0,"5,000,000+",Free,Everyone,Art & Design,"August 3, 2018",2.2.5,4.0.3 and up,194216.0,False,0.0,0.100000